[platformio]
; opzionale: default_envs = esp32-c3-devkitm-1
; copy sdkconfig.defaults into the build sdkconfig before build (works around
; cases where PlatformIO/ESP-IDF doesn't apply sdkconfig_defaults reliably)

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
board_build.sdkconfig_defaults = esp32-c3/sdkconfig.defaults ; il file che già hai in esp32-c3/
; Forcibly use the provided sdkconfig.defaults as the sdkconfig for this build:
;board_build.sdkconfig = esp32-c3/sdkconfig.defaults
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = esp32-c3/partitions.csv
monitor_speed = 115200
build_flags =
    -Os
    -DESP32_C3
    -I include/uart_headers
    -I include/wifi_headers
    -I include/cinematics_header
build_src_filter =  +<src/esp32-c3/> +<src/shared/> -<src/esp32-s3/**>

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = espidf
board_build.sdkconfig_defaults = esp32-s3/sdkconfig.defaults
;board_build.sdkconfig = esp32-s3/sdkconfig.defaults
board_upload.flash_size = 16MB
board_build.partitions = esp32-s3/default_16MB.csv ; usa il csv che già hai
monitor_speed = 115200

build_flags =
    -Os
    -DESP32_S3
    -I include/uart_headers
    -I include/wifi_headers
    -I include/cinematics_header
build_src_filter = +<src/esp32-s3/> +<src/shared/> -<src/esp32-c3/**>
[env:esp32-c3-root]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
board_build.sdkconfig_defaults = esp32-c3/sdkconfig.defaults
board_build.sdkconfig = esp32-c3/sdkconfig.defaults
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = esp32-c3/partitions.csv
monitor_speed = 115200

build_flags =
    -Os
    -DESP32_C3
    -I include/uart_headers
    -I include/wifi_headers
    -I include/cinematics_header
build_src_filter = +<src/esp32-c3/> +<src/shared/> -<src/esp32-s3/**>
board_build.cmake_extra_args = -DC3-ROOT=1


[env:esp32-c3-test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf

;board_build.cmake_dir = tests/esp32-c3/cinematics
board_build.sdkconfig_defaults = esp32-c3/sdkconfig.defaults
board_upload.flash_size = 4MB
board_build.partitions = esp32-c3/partitions.csv

monitor_speed = 115200

board_build.cmake_extra_args = -DTEST_CINEMATICS=1

build_flags =
    -Os
    -DESP32_C3
    -I include/uart_headers
    -I include/wifi_headers
    -I include/cinematics_header

[env:esp32-c3-test-protocol-manager]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf

;board_build.cmake_dir = tests/esp32-c3/protocol_manager
board_build.sdkconfig_defaults = esp32-c3/sdkconfig.defaults
board_upload.flash_size = 4MB
board_build.partitions = esp32-c3/partitions.csv

monitor_speed = 115200

board_build.cmake_extra_args = -DTEST_PROTOCOL_MANAGER=1

build_flags =
    -Os
    -DESP32_C3
    -I include/uart_headers
    -I include/wifi_headers
    -I include/cinematics_header